name: shipping-on-the-air

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - shipping_on_the_air_network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: broker
    depends_on:
      - zookeeper
    networks:
      - shipping_on_the_air_network
    ports:
      - "9092:9092" # For direct Kafka clients
      - "29092:29092" # For host access if needed
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,
        PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  account-service:
    build:
      context: ./account-service
    image: account-service
    container_name: account-service-01
    networks:
      - shipping_on_the_air_network
    ports:
      - "9000:9000"
    expose:
      - 9000
    restart: always
  lobby-service-test:
    build:
      context: ./lobby-service
    image: lobby-service
    container_name: lobby-service-01
    depends_on:
      - account-service
      - kafka
    command: mvn test
    networks:
      - shipping_on_the_air_network
    ports:
      - "9001:9001"
    expose:
      - 9001
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - shipping_on_the_air_network
    ports:
      - "9090:9090"
    expose:
      - 9090
    restart: always
networks:
  shipping_on_the_air_network:
